version: "3.6"
services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./testdata/original:/usr/share/nginx/static

  image_previewer:
    build: "../"
    ports:
      - "8082:8082"
    depends_on:
      - "nginx"